NetBSD support proposal.
SFML/SFML pull request #1723
Opened 2020-12-05 07:42 UTC by devnexen

Thanks a lot for making a contribution to SFML! 🙂

Before you create the pull request, we ask you to check the follow boxes. (For small changes not everything needs to ticked, but the more the better!)

* [ ] Has this change been discussed on [the forum](https://en.sfml-dev.org/forums/index.php#c3) or in an issue before?
* [x] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?
* [ ] Have you provided some example/test code for your changes?
* [ ] If you have additional steps which need to be performed list them as tasks!

2020-12-05 13:24 UTC, eXpl0it3r requested changes
I commented on some small stylistic changes.

As someone with no knowledge or experience with NetBSD, how would I go about testing this?

2020-12-05 13:24 UTC, eXpl0it3r commented on src/SFML/Window/CMakeLists.txt
> +	    ${SRCROOT}/NetBSD/JoystickImpl.hpp
Wrong indentation

2020-12-05 13:24 UTC, eXpl0it3r commented on src/SFML/Window/NetBSD/JoystickImpl.cpp
> +	int id;
Use spaces instead of tabs

2020-12-05 13:24 UTC, eXpl0it3r commented on src/SFML/Window/NetBSD/JoystickImpl.cpp
> +	}
Use spaces instead of tabs

2020-12-05 13:24 UTC, eXpl0it3r commented on src/SFML/Window/NetBSD/JoystickImpl.cpp
> +	    }
Use spaces instead of tabs

2020-12-05 13:24 UTC, eXpl0it3r commented on src/SFML/Window/NetBSD/JoystickImpl.cpp
> +	    if (ioctl(m_file, USB_GET_REPORT_ID, &m_id) < 0) {
`{` should be on a new line

2020-12-05 13:41 UTC, eXpl0it3r commented on cmake/Config.cmake
> +	# don't use the OpenGL ES implementation on NetBSD
Missed one, sorry: Use spaces instead of tab

2020-12-05 14:01 UTC, eXpl0it3r approved these changes

2020-12-05 14:01 UTC, eXpl0it3r commented
SFMLBuildMaster: Build this please.

2020-12-05 15:05 UTC, Bromeon commented
Is there any difference in behavior regarding the different BSD distributions?
If not, we might think about collapsing the config and #define constants.

2020-12-05 15:18 UTC, devnexen commented
Mainly in term of joystick support in this case.

2020-12-06 08:41 UTC, Bromeon commented
Basically, your PR is very similar to the [existing FreeBSD joystick implementation](https://github.com/SFML/SFML/blob/master/src/SFML/Window/FreeBSD/JoystickImpl.cpp), in small differences e.g. how to get joystick ID. Meanwhile, the [OpenBSD implementation](https://github.com/SFML/SFML/blob/master/src/SFML/Window/OpenBSD/JoystickImpl.cpp) is an empty stub.

But in this case I'm not sure if it makes things more complicated to unify common code rather than duplicating it. The only thing I could imagine is if there is some `Window/BSD` folder with shared code -- not sure if it's worth it.

By the way, do you happen to know if the same code can be used on OpenBSD?

2020-12-06 09:26 UTC, devnexen commented
> 
> By the way, do you happen to know if the same code can be used on OpenBSD?

It might ... maybe the only difference is the ioctl lookup id, just a glance in their code tree tough.

2020-12-06 12:41 UTC, eXpl0it3r commented
I my opinion, code duplication is okay, if it's for the sake of isolating independent contexts/modules/etc.
Maybe there's a way to make share more code between the different BSD versions, but I think that should then maybe be done as a separate PR.

2020-12-07 15:08 UTC, merged

2020-12-07 15:08 UTC, eXpl0it3r commented
Thank you for the contribution! 🙂