Strategic use of '[[nodiscard]]' in 'System' module
SFML/SFML pull request #1890
Opened 2021-12-09 16:22 UTC by vittorioromeo

## Description

A more targeted approach to `[[nodiscard]]` compared to #1883. This has been done completely manually, applying the attribute to functions where is either not obvious that the return value is significant or where it would be a bug to forget to handle it.

I did not touch the threading primitives as they will be removed with #1863.

## Tasks

* [ ] Tested on Linux
* [x] Tested on Windows
* [ ] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

## How to test this PR?

CI.

2021-12-13 20:11 UTC, eXpl0it3r requested changes

2021-12-13 20:32 UTC, eXpl0it3r approved these changes

2021-12-13 22:08 UTC, binary1248 requested changes

2021-12-13 22:08 UTC, binary1248 commented on src/SFML/Audio/SoundFileReaderWav.cpp
> +    }
No curly braces around single statement if body.

2021-12-13 22:08 UTC, binary1248 commented on src/SFML/Graphics/ImageLoader.cpp
> +        }
No curly braces around single statement if body.

2021-12-13 22:08 UTC, binary1248 commented on src/SFML/System/FileInputStream.cpp
> +        }
No curly braces around single statement if body.

2021-12-14 12:11 UTC, vittorioromeo commented on src/SFML/Audio/SoundFileReaderWav.cpp
> +    }
Fixed

2021-12-14 12:11 UTC, vittorioromeo commented on src/SFML/Graphics/ImageLoader.cpp
> +        }
Fixed

2021-12-14 12:11 UTC, vittorioromeo commented on src/SFML/System/FileInputStream.cpp
> +        }
Fixed

2021-12-14 12:34 UTC, binary1248 approved these changes

2021-12-14 13:02 UTC, merged