Replace Catch with Doctest
SFML/SFML pull request #1921
Opened 2021-12-21 00:01 UTC by vittorioromeo

This PR changes the testing framework from Catch to doctest, mostly to improve compilation times and reduce the load onCI. The results speak for themselves:

<details>
<summary>Compilation time analysis with Catch</summary>

Analyzing build trace from 'analysis.txt'...
**** Time summary:
Compilation (225 times):
  Parsing (frontend):          149.8 s
  Codegen & opts (backend):     71.3 s

**** Files that took longest to parse (compiler frontend):
  4903 ms: test/CMakeFiles/test-sfml-system.dir/src/CatchMain.cpp.obj
  4295 ms: test/CMakeFiles/test-sfml-window.dir/src/CatchMain.cpp.obj
  4020 ms: test/CMakeFiles/sfml-test-main.dir/src/CatchMain.cpp.obj
  3678 ms: test/CMakeFiles/test-sfml-graphics.dir/src/CatchMain.cpp.obj
  3359 ms: test/CMakeFiles/test-sfml-network.dir/src/CatchMain.cpp.obj
  3216 ms: src/SFML/Window/CMakeFiles/sfml-window.dir/WindowImpl.cpp.obj
  2675 ms: src/SFML/Window/CMakeFiles/sfml-window.dir/GlContext.cpp.obj
  2624 ms: src/SFML/Window/CMakeFiles/sfml-window.dir/EglContext.cpp.obj
  2418 ms: src/SFML/Window/CMakeFiles/sfml-window.dir/Win32/JoystickImpl.cpp.obj
  2349 ms: test/CMakeFiles/test-sfml-system.dir/src/System/Vector2.cpp.obj

**** Files that took longest to codegen (compiler backend):
  8046 ms: src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/ImageLoader.cpp.obj
  6334 ms: test/CMakeFiles/test-sfml-window.dir/src/CatchMain.cpp.obj
  6235 ms: test/CMakeFiles/test-sfml-system.dir/src/CatchMain.cpp.obj
  6216 ms: test/CMakeFiles/test-sfml-graphics.dir/src/CatchMain.cpp.obj
  6137 ms: test/CMakeFiles/test-sfml-network.dir/src/CatchMain.cpp.obj
  4759 ms: test/CMakeFiles/sfml-test-main.dir/src/CatchMain.cpp.obj
  3071 ms: examples/opengl/CMakeFiles/opengl.dir/OpenGL.cpp.obj
  2330 ms: examples/window/CMakeFiles/window.dir/Window.cpp.obj
  2057 ms: src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/GLExtensions.cpp.obj
  1964 ms: src/SFML/Audio/CMakeFiles/sfml-audio.dir/SoundFileReaderMp3.cpp.obj

**** Templates that took longest to instantiate:
   750 ms: std::basic_string<char16_t>::_M_construct<const char16_t *> (186 times, avg 4 ms)
   732 ms: std::basic_string<char32_t>::_M_construct<const char32_t *> (186 times, avg 3 ms)
   705 ms: std::unordered_map<int, int> (39 times, avg 18 ms)
   598 ms: std::_Hashtable<int, std::pair<const int, int>, std::allocator<std::... (39 times, avg 15 ms)
   594 ms: __gnu_cxx::__to_xstring<std::basic_string<wchar_t>, wchar_t> (93 times, avg 6 ms)
   506 ms: std::basic_string<wchar_t>::_M_construct<wchar_t *> (186 times, avg 2 ms)
   497 ms: std::basic_string<char32_t> (93 times, avg 5 ms)
   487 ms: std::basic_string<char32_t>::basic_string (93 times, avg 5 ms)
   471 ms: std::basic_string<wchar_t> (93 times, avg 5 ms)
   469 ms: std::basic_string<char16_t>::basic_string (93 times, avg 5 ms)
   446 ms: std::basic_string<char16_t> (93 times, avg 4 ms)
   444 ms: __gnu_cxx::__to_xstring<std::basic_string<char>, char> (93 times, avg 4 ms)
   415 ms: std::basic_string<char> (93 times, avg 4 ms)
   378 ms: std::basic_string<char16_t>::_M_construct_aux<const char16_t *> (93 times, avg 4 ms)
   364 ms: std::basic_string<wchar_t>::basic_string<wchar_t *, void> (93 times, avg 3 ms)
   359 ms: std::basic_string<char32_t>::_M_construct_aux<const char32_t *> (93 times, avg 3 ms)
   350 ms: std::operator+<char, std::char_traits<char>, std::allocator<char>> (197 times, avg 1 ms)
   281 ms: std::basic_string<char>::_M_construct<char *> (185 times, avg 1 ms)
   274 ms: std::__and_<std::is_convertible<const char16_t *const &, std::basic_... (93 times, avg 2 ms)
   256 ms: std::basic_string_view<char> (93 times, avg 2 ms)
   254 ms: std::__detail::__hyperg<float> (25 times, avg 10 ms)
   251 ms: std::basic_string<wchar_t>::_M_construct_aux<wchar_t *> (93 times, avg 2 ms)
   243 ms: std::__detail::_Insert<int, std::pair<const int, int>, std::allocato... (39 times, avg 6 ms)
   232 ms: std::basic_string<char>::basic_string (190 times, avg 1 ms)
   230 ms: std::unordered_multimap<int, int> (39 times, avg 5 ms)
   223 ms: std::__detail::_Insert_base<int, std::pair<const int, int>, std::all... (39 times, avg 5 ms)
   214 ms: std::__and_<std::is_convertible<const char32_t *const &, std::basic_... (93 times, avg 2 ms)
   211 ms: std::__detail::__hyperg<long double> (25 times, avg 8 ms)
   207 ms: std::unique_ptr<std::thread::_State> (11 times, avg 18 ms)
   205 ms: std::pair<bool, unsigned long long> (45 times, avg 4 ms)

**** Template sets that took longest to instantiate:
  3270 ms: std::__and_<$> (2201 times, avg 1 ms)
  1992 ms: std::basic_string<$> (405 times, avg 4 ms)
  1492 ms: std::_Hashtable<$> (147 times, avg 10 ms)
  1431 ms: std::basic_string<$>::_M_construct<$> (565 times, avg 2 ms)
  1312 ms: std::basic_string<$>::basic_string (474 times, avg 2 ms)
  1310 ms: std::basic_string<$>::_M_construct_aux<$> (559 times, avg 2 ms)
  1299 ms: std::unordered_map<$> (81 times, avg 16 ms)
  1232 ms: __gnu_cxx::__stoa<$> (1442 times, avg 0 ms)
  1226 ms: std::__or_<$> (1386 times, avg 0 ms)
  1103 ms: std::is_convertible<$> (1239 times, avg 0 ms)
  1038 ms: __gnu_cxx::__to_xstring<$> (186 times, avg 5 ms)
   904 ms: std::vector<$>::push_back (141 times, avg 6 ms)
   803 ms: std::pair<$> (267 times, avg 3 ms)
   799 ms: std::basic_string_view<$> (375 times, avg 2 ms)
   746 ms: std::vector<$>::_M_realloc_insert<$> (146 times, avg 5 ms)
   718 ms: std::vector<$> (260 times, avg 2 ms)
   656 ms: std::basic_string<$>::basic_string<$> (283 times, avg 2 ms)
   623 ms: std::__not_<$> (662 times, avg 0 ms)
   589 ms: std::chrono::duration<$> (441 times, avg 1 ms)
   571 ms: std::__detail::_Insert<$> (127 times, avg 4 ms)
   506 ms: std::unique_ptr<$> (26 times, avg 19 ms)
   503 ms: std::__detail::_Insert_base<$> (103 times, avg 4 ms)
   478 ms: std::is_nothrow_default_constructible<$> (404 times, avg 1 ms)
   466 ms: std::__detail::__hyperg<$> (50 times, avg 9 ms)
   420 ms: std::is_trivial<$> (377 times, avg 1 ms)
   418 ms: std::__uniq_ptr_data<$> (26 times, avg 16 ms)
   411 ms: std::__detail::_Hashtable_alloc<$> (99 times, avg 4 ms)
   403 ms: std::__uniq_ptr_impl<$> (26 times, avg 15 ms)
   369 ms: std::vector<$>::_S_use_relocate (155 times, avg 2 ms)
   369 ms: std::vector<$>::~vector (165 times, avg 2 ms)

**** Functions that took longest to compile:
   980 ms: main (C:/OHW/SFML/examples/opengl/OpenGL.cpp)
   514 ms: ____C_A_T_C_H____T_E_S_T____0() (C:/OHW/SFML/test/src/System/Vector3.cpp)
   514 ms: gladLoadGLUserPtr(void (* (*)(void*, char const*))(), void*) (C:/OHW/SFML/src/SFML/Graphics/GLExtensions.cpp)
   493 ms: Catch::makeCommandLineParser() (C:/OHW/SFML/test/src/CatchMain.cpp)
   440 ms: ____C_A_T_C_H____T_E_S_T____0() (C:/OHW/SFML/test/src/System/Vector2.cpp)
   402 ms: mp3dec_decode_frame (C:/OHW/SFML/src/SFML/Audio/SoundFileReaderMp3.cpp)
   372 ms: stbi__jpeg_load(stbi__context*, int*, int*, int*, int, stbi__result_... (C:/OHW/SFML/src/SFML/Graphics/ImageLoader.cpp)
   356 ms: ____C_A_T_C_H____T_E_S_T____0() (C:/OHW/SFML/test/src/Graphics/Rect.cpp)
   289 ms: main (C:/OHW/SFML/examples/window/Window.cpp)
   270 ms: stbi__create_png_image_raw(stbi__png*, unsigned char*, unsigned int,... (C:/OHW/SFML/src/SFML/Graphics/ImageLoader.cpp)
   254 ms: gladLoadGLUserPtr (C:/OHW/SFML/examples/window/Window.cpp)
   235 ms: glad_gl_resolve_aliases() (C:/OHW/SFML/examples/window/Window.cpp)
   209 ms: gladLoadGL (C:/OHW/SFML/examples/window/Window.cpp)
   199 ms: stbi__load_main(stbi__context*, int*, int*, int*, int, stbi__result_... (C:/OHW/SFML/src/SFML/Graphics/ImageLoader.cpp)
   187 ms: Catch::ConsoleReporter::printTotals(Catch::Totals const&) (C:/OHW/SFML/test/src/CatchMain.cpp)
   183 ms: Catch::listTests(Catch::Config const&) (C:/OHW/SFML/test/src/CatchMain.cpp)
   172 ms: Catch::listTags(Catch::Config const&) (C:/OHW/SFML/test/src/CatchMain.cpp)
   138 ms: gladLoadGLUserPtr (C:/OHW/SFML/examples/opengl/OpenGL.cpp)
   128 ms: stbi__tga_load(stbi__context*, int*, int*, int*, int, stbi__result_i... (C:/OHW/ [...]

2021-12-21 00:06 UTC, Bromeon commented
Thanks for trying this out.

Do you know of any other trade-offs (pros + cons) of doctest vs. Catch2?
I've seen the [FAQ](https://github.com/doctest/doctest/blob/master/doc/markdown/faq.md#how-is-doctest-different-from-catch) on their GitHub page, but do you (or anybody) have personal experience with doctest?

2021-12-21 00:10 UTC, vittorioromeo commented
I have personally used doctest both at work and in some personal projects (currently private repositories). I've never needed any advanced feature, but it does the job well for all my testing needs. I have used Catch in the past but after switching to doctest I have no reason to go back, it is just faster.

> While compile times are better in SFML, it's nowhere near the "20 times" or "many times" advertised in the FAQ -- which in turn makes me skeptical how accurate their other promises are.

Their claims are not bogus. Check the analyses that I posted in the OP -- Catch dominates a huge chunk of the first compilation process analysis, and doctest doesn't even appear in the second one! Note that my analyses and timings are for a full complete build of SFML, including examples and tests. The benchmarks on doctest are way more specialized.

2021-12-21 01:21 UTC, binary1248 commented
I remember trying out doctest the first time I heard of it at one of the author's presentations. I too noticed a perceivable build time improvement, especially when compared to Catch 1 (which was known for having bad build times back then). Although the library promotes writing the tests right next to the code I never really got used to that idea. I am not against replacing Catch2 with doctest if it offers many benefits to us given the current way our unit tests are written.

2021-12-21 09:43 UTC, vittorioromeo commented
> I remember trying out doctest the first time I heard of it at one of the author's presentations. I too noticed a perceivable build time improvement, especially when compared to Catch 1 (which was known for having bad build times back then). Although the library promotes writing the tests right next to the code I never really got used to that idea. I am not against replacing Catch2 with doctest if it offers many benefits to us given the current way our unit tests are written.

I am not suggesting changing the way we write unit tests, I don't like putting them next to the code either. The benefits of this PR are strictly about improving compilation times and reducing CI load -- I think the benchmarks are quite impressive.

2021-12-21 18:58 UTC, vittorioromeo commented
Note that doctest doesn't need the workaround for MinGW introduced in #1898, as well.

2021-12-21 19:12 UTC, ChrisThrasher commented
How much of a bottleneck is building tests? I'm slowly getting up to speed with how CI is being handled with SFML but it appears that by far the biggest bottleneck to PRs are the non-GitHub CI jobs that seemingly take 10x longer than the GitHub jobs. Does this project only get so many minutes of CI time per month that we're trying to optimize or what? Does this PR significantly speed up those other jobs that currently take so long to complete?

2021-12-21 19:33 UTC, vittorioromeo commented
> How much of a bottleneck is building tests? I'm slowly getting up to speed with how CI is being handled with SFML but it appears that by far the biggest bottleneck to PRs are the non-GitHub CI jobs that seemingly take 10x longer than the GitHub jobs. Does this project only get so many minutes of CI time per month that we're trying to optimize for? Does this PR meaningfully speed up those other jobs that currently take so long to complete?

I have not measured the time it takes to perform a full CI run prior and after this PR. However, on my local machine a full rebuild of SFML is 4s faster after this PR.  There are 47 CI checks. If we save a similar amount of time on a CI machine, we could be looking at around 188s of total time save. (@binary1248: any way we could measure that?)

Regardless, I would ask a different question: if both Catch2 and doctest provide the functionality that we require, but one is clearly faster to compile than the other, and transitioning from one to the other is trivial... why would we ever choose to pick the slower one?

2021-12-23 20:13 UTC, vittorioromeo commented
@eXpl0it3r, @Bromeon: could you approve this before we start making more contributions to the testing part of SFML (e.g. #1933 )?

2021-12-24 09:21 UTC, eXpl0it3r commented
@ChrisThrasher are you okay if we merge this soon and have your PRs having to be adapted to doctest?

2021-12-24 09:22 UTC, Bromeon approved these changes
I'm OK with this change.

Are there more objections, in favor of Catch2? @ChrisThrasher @eXpl0it3r or so?

2021-12-24 09:25 UTC, eXpl0it3r requested changes
This should be removed again, unless MinGW struggles as well with Doctest

https://github.com/SFML/SFML/blob/cd1cc62f6d4ad06543e2e2cc2feebd466c1dc827/test/CMakeLists.txt#L16-L19

2021-12-24 09:41 UTC, Bromeon commented
What we should keep in mind: the future of Doctest is not very clear at this point -- https://github.com/doctest/doctest/issues/554
I hope that they find someone to maintain the project though 🚀

2021-12-24 13:27 UTC, ChrisThrasher commented
> are you okay if we merge this soon and have your PRs having to be adapted to doctest?
 
I'm fine adapting my MRs. Looks like a simple find-replace to make the switch.

> What we should keep in mind: the future of Doctest is not very clear at this point

I'm not excited about the prospect of adopting a library without a clear maintenance plan just to save a few seconds of compile time, but I won't object to this.

2021-12-24 13:33 UTC, vittorioromeo commented
> This should be removed again, unless MinGW struggles as well with Doctest
> 
> https://github.com/SFML/SFML/blob/cd1cc62f6d4ad06543e2e2cc2feebd466c1dc827/test/CMakeLists.txt#L16-L19

Done. I remember it didn't need big-obj, but let's see if CI agrees.

---

> What we should keep in mind: the future of Doctest is not very clear at this point -- [doctest/doctest#554](https://github.com/doctest/doctest/issues/554) Even then, at present it looks like a robust library. I hope that they find someone to maintain the project 🚀

Ditto... reverting to Catch is always an option if we ever need to, it would be easy to do.

2021-12-24 14:06 UTC, eXpl0it3r approved these changes

2021-12-24 14:06 UTC, merged

2021-12-29 10:04 UTC, onqtam commented
Pretty cool to see these results! Indeed the benchmarks in doctest are synthetic - they measure the compile time of simple translation units including only the framework header and nothing from the stdlib. I'm quite hopeful that the framework has a future!