Add sf::PrimitiveInfo
SFML/SFML pull request #1992
Opened 2022-02-02 02:12 UTC by Marioalexsan

Thanks a lot for making a contribution to SFML! 🙂

Before you create the pull request, we ask you to check the follow boxes. (For small changes not everything needs to ticked, but the more the better!)

* [ ] Has this change been discussed on [the forum](https://en.sfml-dev.org/forums/index.php#c3) or in an issue before?
* [X] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?
* [X] Have you provided some example/test code for your changes?
* [ ] If you have additional steps which need to be performed list them as tasks!

----

## Description

This PR adds the `sf::PrimitiveInfo` interface, which allows extracting vertex info from drawables. The interface is implemented for every drawable except `sf::VertexBatch`. This allows users to use SFML's drawables together with custom render logic (such as sprite batching), instead of recreating all of the logic using `sf::VertexArray` in specialized classes.

## Tasks

* [ ] Tested on Linux
* [X] Tested on Windows
* [ ] Tested on macOS
* [ ] Tested on iOS
* [ ] Tested on Android

## How to test this PR?

Render some drawables using this code. You will need a TTF and a PNG:
```cpp
#include <SFML/Graphics.hpp>

int main()
{
    sf::RenderWindow window(sf::VideoMode(1280, 720), "PrimitiveInfo", sf::Style::Default);
    window.setView({ { 0, 0 }, { 1280, 720 } });

    sf::Font font;
    sf::Texture texture;

    if (!font.loadFromFile("Font0.ttf") || !texture.loadFromFile("Texture0.png"))
    {
        sf::err() << "Oh no!";
        return 0;
    }

    sf::Text text("Primitives are cool", font, 30);
    text.setPosition({ 0, 0 });

    sf::Sprite sprite(texture);
    sprite.setPosition({ 200, 0 });

    sf::CircleShape shape(100, 6);
    shape.setPosition({ 400, 0 });
    shape.setTexture(&texture);

    const sf::Texture* drawTexture;
    sf::Transform transform;

    auto renderer = [&text, &window, &drawTexture, &transform](std::vector<sf::Vertex>& vertices, sf::PrimitiveType type)
    {
        for (auto& vertex : vertices)
        {
            vertex.position = transform.transformPoint(vertex.position);
        }

        window.draw(vertices.data(), vertices.size(), type, sf::RenderStates(drawTexture));
    };

    drawTexture = &text.getFont()->getTexture(text.getCharacterSize());
    transform = text.getTransform();

    text.forEachMutablePrimitive(renderer);

    drawTexture = sprite.getTexture();
    transform = sprite.getTransform();

    sprite.forEachMutablePrimitive(renderer);

    drawTexture = shape.getTexture();
    transform = shape.getTransform();

    shape.forEachMutablePrimitive(renderer);

    window.display();

    sf::sleep(sf::seconds(6));
}
```

2022-02-02 08:39 UTC, eXpl0it3r commented
SFMLBuildMaster: Build this please.

2022-02-02 10:15 UTC, Bromeon commented
Thanks for your contribution!

This seems to be a highly specialized API, and the callback-based approach is rather unconventional for SFML's style. Also, transform being outside the callback is probably not that useful, as transforms (unlike textures) are rarely reused across a large number of `sf::Drawable` objects (except in `sf::VertexArray`).

What is the concrete use case you have in mind? Are you using this pattern in an application?
The example code you show is mostly `window.draw()` with extra steps 🙂

2022-02-02 11:24 UTC, Marioalexsan commented
The test code is lame indeed... A better use for this API is to implement sprite batches. The main benefit is that one can use SFML's drawables (or custom drawables) directly, instead of reimplementing `sf::Sprite` or using `sf::VertexArray` with custom logic.

The concrete use case for this API would be to implement sprite batches. I have created this [repo](https://github.com/Marioalexsan/SFMLBatchTest/blob/master/GraphicsBatch.cpp) that uses the PrimitiveInfo API to batch sprites and other things.

This [repo](https://github.com/ricanteja/Moony-SpriteBatch) is an example of where sprite batching is implemented

2022-02-02 11:34 UTC, Marioalexsan commented
The main use case of this API would be to implement sprite batches that can work directly with SFML's drawables. Currently, users have to roll their own logic using `sf::VertexArray` and reimplement `sf::Sprite` and `sf::Text` to be batchable. For example, [this repository](https://github.com/ricanteja/Moony-SpriteBatch/tree/master/source) uses a custom (and probably incomplete) Sprite class. #1802 uses `sf::VertexArray`, which would also require users to reimplement drawables.

While I don't have any cool production code or anything, I have [this sprite batch class](https://github.com/Marioalexsan/SFMLBatchTest/blob/master/GraphicsBatch.cpp) that utilizes the API. While the test case is lame (since it's just a fancy `window.draw()` like you mentioned), the batch class defers rendering until `batch.end()` is called, where it can reorder sprites and render them with less render state switching.

2022-02-03 19:15 UTC, vittorioromeo requested changes
C++-related changes. Have not thought about the use cases for this feature yet.

2022-02-03 19:15 UTC, vittorioromeo commented on include/SFML/Graphics/PrimitiveInfo.hpp
> +    typedef std::function<void(const Vertex* vertices, std::size_t vertexCount, PrimitiveType type)> PrimitiveCallback;
```suggestion
    using PrimitiveCallback = std::function<void(const Vertex* vertices, std::size_t vertexCount, PrimitiveType type)>;
```

2022-02-03 19:15 UTC, vittorioromeo commented on include/SFML/Graphics/PrimitiveInfo.hpp
> +    typedef std::function<void(std::vector<Vertex>& vertices, PrimitiveType type)> MutablePrimitiveCallback;
```suggestion
    using MutablePrimitiveCallback = std::function<void(std::vector<Vertex>& vertices, PrimitiveType type)>;
```

2022-02-03 19:15 UTC, vittorioromeo commented on include/SFML/Graphics/PrimitiveInfo.hpp
> +    virtual void forEachPrimitive(PrimitiveCallback callback) const = 0;
```suggestion
    virtual void forEachPrimitive(const PrimitiveCallback& callback) const = 0;
```

2022-02-03 19:15 UTC, vittorioromeo commented on include/SFML/Graphics/PrimitiveInfo.hpp
> +    void forEachMutablePrimitive(MutablePrimitiveCallback callback) const;
```suggestion
    void forEachMutablePrimitive(const MutablePrimitiveCallback& callback) const;
```

2022-02-03 19:15 UTC, vittorioromeo commented on src/SFML/Graphics/PrimitiveInfo.cpp
> +        }
```suggestion
        vec.assign(vertices, vertices + vertexCount);
```

2022-02-19 18:48 UTC, Marioalexsan commented
I'm not really satisfied with my approach, so I'll clean this up and open another pull request when ready.

2022-02-19 18:48 UTC, closed without merging

2022-02-20 14:15 UTC, Bromeon commented
Maybe it makes sense to discuss the design first (in an issue or on the forum). Not that you put all the effort into a PR and then have to throw it away.