Add warning about XButton1 and 2 on X11.
SFML/SFML pull request #2038
Opened 2022-03-08 14:04 UTC by MrZeusTheCoder

* [X] Has this change been discussed on [the forum](https://en.sfml-dev.org/forums/index.php#c3) or in an issue before? Yes at https://en.sfml-dev.org/forums/index.php?topic=28414
* [X] Does the code follow the SFML [Code Style Guide](https://www.sfml-dev.org/style.php)?

----

## Description

Adds a warning about the two XButtons not being polled on Linux. This closes a task for 2.6.0.

2022-03-08 14:24 UTC, kimci86 commented
The linked forum post tells that `XButton1` and `XButton2` are not detected with `isButtonPressed` but work well with `sf::Event`. Only the real-time polling is not available, so a warning would maybe better fit in `isButtonPressed` documentation.

2022-03-15 00:56 UTC, MrZeusTheCoder commented
There is no chance I will get around to this before next week.

2022-04-19 06:42 UTC, eXpl0it3r commented
I've rebased your commit onto `2.6.x` and updated the target branch 🙂

2022-04-19 06:42 UTC, eXpl0it3r approved these changes

2022-04-19 06:45 UTC, eXpl0it3r requested changes
Just got reminded of @kimci86's comment about the original report...

2022-04-19 06:45 UTC, eXpl0it3r commented on include/SFML/Window/Mouse.hpp
> +        XButton2,   //!< The second extra mouse button (not available on Linux)
As pointed out by @kimci86, these buttons are available through events, so I guess we might not want to have this here

2022-04-19 06:45 UTC, eXpl0it3r commented on include/SFML/Window/Mouse.hpp
> +///
As pointed out by @kimci86, these buttons are available through events, so we might want to move this warning to `isButtonPressed` instead

2022-06-15 10:40 UTC, vittorioromeo commented
@MrZeusTheCoder: are you interested in continuing work on this PR?

2022-06-18 17:33 UTC, MrZeusTheCoder commented
No, sorry about this all. Life has been crazy!

2022-06-18 17:33 UTC, closed without merging