Unify float literal usage in tests
SFML/SFML pull request #2125
Opened 2022-06-08 17:31 UTC by ChrisThrasher

## Description

The inconsistent use of numeric literals is 100% the fault of whoever has been writing all these unit tests so run `git blame` and yell at that idiot. Unifying how we use literals also has the knock-on effect of removing tons of code (as measured by character count) which has readability gains. For anyone curious about the `int` -> `float` conversion, this is 100% safe because these `int` literals are known by the compiler to convert losslessly to `float`s so there's no correctness lost in this PR.

## Tasks

* [x] Tested on Linux
* [x] Tested on Windows
* [x] Tested on macOS
* [x] Tested on iOS
* [x] Tested on Android

2022-06-08 20:26 UTC, Bromeon commented
Sorry for always nitpicking on stylistic issues, I feel bad given the huge effort you have put into SFML over the last months 😬

One issue with using integer literals as floats is that we might not be able to do that 100% of the time (thus not fully "unifying" things). Examples I can imagine are arguments to generic functions, overloaded functions, `{ }` initialization syntax (like `{2, 1}` for vectors), etc.

Other than that it's probably fine, as long as people agree it's more readable that way. I usually write the `.f` explicitly, but that might also be a habit stemming from old compilers, which issued warnings for such cases.

2022-06-08 20:37 UTC, ChrisThrasher commented
> One issue with using integer literals as floats is that we might not be able to do that 100% of the time (thus not fully "unifying" things).

Maybe "unify" is the wrong word here. I mostly just wanted to make code less verbose wherever possible. I said "unify" because in earlier unit tests I was always adding `.0f` then realized I could just do `.f` _then_  I realized could actually just use integer literals in most places so if you look closely, the style of the unit tests I wrote shifted over time to get marginally simpler. 

> One issue with using integer literals as floats is that we might not be able to do that 100% of the time (thus not fully "unifying" things). Examples I can imagine are arguments to generic functions, overloaded functions, { } initialization syntax (like {2, 1} for vectors), etc.

In a few places I had to be sure I wasn't accidentally calling a different overload but for the most part SFML doesn't overload on `float`s and `int`s. 

> Other than that it's probably fine, as long as people agree it's more readable that way. I usually write the .f explicitly, but that might also be a habit stemming from old compilers, which issued warnings for such cases.

I'm cool with anything so long as we're not requiring the trailing `0` after the decimal point. I know I'm getting _really_ into the weeds with this but I figured it was worth a PR cleaning up the mess I made in `test/` even if we don't make a point to maintain a specific style going forward.

2022-06-08 20:39 UTC, Bromeon commented
Sounds good. I'm personally all for readable tests! It's just that this may be highly subjective, some people prefer things to be "explicit but more verbose". I'm fine either way here, concise tests means also they are slightly more motivating to write 🙂

2022-06-08 20:46 UTC, ChrisThrasher commented
> It's just that this may be highly subjective

This is probably a one-time change since maintaining such rigorous consistency with `float` literals will be painfully tedious. 

For what it's worth, `src/` and `include/` are already very consistent with `float` literals. `examples/` has a significant number of inconsistencies but there aren't meaningful readability gains to be made there. Fixing that up is mostly an academic exercise. I omitted those changes from this PR for the sake keep scope from exploding.

2022-06-08 20:51 UTC, Bromeon commented
Hm, there's probably no tooling available to automate that? Like a linter with a built-in "fix" mode? 🔧

2022-06-08 20:54 UTC, ChrisThrasher commented
Not that I'm aware of. clang-tidy has a built-in fix mode but clang-tidy doesn't address these kinds of discrepancies. As an aside, I've played around with running clang-tidy over SFML and eventually want to add that to our CI pipeline.

2022-06-08 21:07 UTC, eXpl0it3r commented
SFMLBuildMaster: Build this please.

2022-06-08 21:51 UTC, eXpl0it3r commented
I personally prefer `1.f` etc as well, as it's more explicit of what I'm wanting to achieve and removes the need to differentiate if there are int and float overloads.

2022-06-09 09:22 UTC, vittorioromeo commented
I'll bite -- if we need a float expression, isn't it better to explicitly use a float literal rather than using an integer literal and relying on an implicit conversion...? The former seems more sensible to me.

2022-06-09 15:22 UTC, ChrisThrasher commented
2 votes to 1 from the maintainers so it looks like we have a decision. I still want to remove all the instances of `.0f` I added but I'll replace those with `.f` instead.

2022-06-09 19:02 UTC, eXpl0it3r commented
SFMLBuildMaster: Build this please.

2022-06-10 06:37 UTC, eXpl0it3r requested changes
Looks like not all `sf::Transform` constructor call used float literals to begin with 🤔

2022-06-10 06:37 UTC, eXpl0it3r commented on test/Graphics/Transform.cpp
> +        CHECK(transform.translate({10.f, 20.f}) == sf::Transform(9, 8, 507, 6, 5, 324, 3, 2, 141));
Shouldn't these be floats as well in the Transform constructor?

2022-06-10 06:37 UTC, eXpl0it3r commented on test/Graphics/Transform.cpp
> +            CHECK(transform.scale({10.f, 10.f}) == sf::Transform(0, 0, 3, 0, 0, 4, 0, 0, 1));
Shouldn't these be floats as well in the Transform constructor?

2022-06-10 06:37 UTC, eXpl0it3r commented on test/Graphics/Transform.cpp
> +            CHECK(transform.scale({0.f, 0.f}, {1.f, 0.f}) == sf::Transform(0, 0, 4, 0, 0, 8, 0, 0, 4));
Shouldn't these be floats as well in the Transform constructor?

2022-06-10 06:41 UTC, ChrisThrasher commented
> Looks like not all sf::Transform constructor call used float literals to begin with

Haha I was wondering if anyone would notice that. In my latest tests I started using loads of integer literals, hence this PR. Sadly I can't easy grep for integer literals that are being used to initialize `float`s but I can go through and find and fix those.

2022-06-10 07:36 UTC, Bromeon commented
Looks like you opened Pandora's Box 😁

2022-06-10 07:37 UTC, ChrisThrasher commented
I guess I deserve this for opening the PR ¯\_(ツ)_/¯

2022-06-10 19:21 UTC, ChrisThrasher commented
I added `.f` in about a hundred more places. Let me know if there's anything I missed.

2022-06-10 19:40 UTC, ChrisThrasher commented
I found a few hundred more places where float literals could be used. The current state of this PR illustrates why I've been using integer literals. I don't think hundreds of unnecessary `.f` suffixes make the code any easier to read. Plus it's just a huge pain to audit the code for missing `.f` suffixes whereas finding and removing unnecessary `.f` suffixes is pretty easy to enforce.

2022-06-10 19:55 UTC, Bromeon commented
Guys, I know it's "correct" but are we solving a real problem here? Readability _is_ subjective and while there _may_ be obscure corner-case bugs related to incorrect float/integer literal usage, I have the feeling this is a bit of an academic exercise. Especially since the other literals haven't been more correct in C++98, yet no one has complained -- at least to my knowledge.

Talking of readability, a bigger pain imho is the proliferation of `static_cast<Type>(expression)` all over the place. I know it's often unavoidable, but even things like `toUint8(expression)` would help a lot; but I know this is also controversial.

Yet even that is a relatively small issue. I'm not sure if we shouldn't focus our resources on more pressing issues which add real value to users -- like coming to a consensus on the long overdue scancode design.

2022-06-10 20:01 UTC, ChrisThrasher commented
I'm definitely sucking up much of the oxygen in the room with this PR and maybe regret opening it. This is far from my top priority so if we can't come to a consensus on this I'm fine closing this. I'd also much rather we spend our time discussing scancodes or SFML 3 design decisions. I've tried proposing some bigger changes I want to make but haven't gotten very much feedback, hence me filling my time with these lesser important PRs.

2022-06-13 13:35 UTC, closed without merging