Remove default empty state of `sf::Font`
SFML/SFML pull request #3020
Opened 2024-05-18 17:55 UTC by ChrisThrasher

## Description

This is the first step towards replacing the `loadFromFile` family of member functions with factory functions. There is no use case for a default-constructed `sf::Font` so this PR systematically eliminates a category of bug where users forget to or fail to initialize a font.

In our examples I chose to use `.value()` to extract the font from the `std::optional<sf::Font>`. This has the same effect as returning `EXIT_FAILURE` since in both cases the program is immediately terminated with a non-zero error code. I chose to make that same recommendation in the documentation since I think it's the best default choice for users who don't otherwise know how to handle such errors.

This method of error handling was decided upon in https://github.com/SFML/SFML/issues/2139.

Supersedes https://github.com/SFML/SFML/pull/2231 which has accumulated conflicts.

2024-05-18 17:59 UTC, ChrisThrasher commented on include/SFML/Graphics/Font.hpp
> -    void cleanup();
If an API refactor lets us remove manual cleanup functions then we know we're doing something right.

2024-05-19 16:28 UTC, vittorioromeo requested changes
Great change! This makes the API much nicer and safer to use. The only thing I think we can improve is that we don't need a default constructor at all, we always need font handles and a family name to construct the font AFAICS. Please let me know if I am mistaken!

2024-05-19 16:28 UTC, vittorioromeo commented on include/SFML/Graphics/Font.hpp
> +    Font() = default;
```suggestion
    ////////////////////////////////////////////////////////////
    /// \brief Create a font from font handles and a family name
    ///
    ////////////////////////////////////////////////////////////
    explicit Font(std::shared_ptr<FontHandles>&& fontHandles, std::string&& familyName);
```

2024-05-19 16:28 UTC, vittorioromeo commented on src/SFML/Graphics/Font.cpp
> +    return font;
GitHub won't let me suggest here, but:

```cpp
return Font(std::move(fontHandles), std::string(face->family_name ? face->family_name : ""));

2024-05-19 16:28 UTC, vittorioromeo commented on src/SFML/Graphics/Font.cpp
> +    return font;
GitHub won't let me suggest here, but:

```cpp
return Font(std::move(fontHandles), std::string(face->family_name ? face->family_name : ""));

2024-05-19 16:28 UTC, vittorioromeo commented on src/SFML/Graphics/Font.cpp
> +    return loadFromStream(*font.m_stream);
```suggestion
    auto stream = std::make_shared<priv::ResourceStream>(filename);
    
    auto font = loadFromStream(*stream);
    font.m_stream = std::move(stream)
    return font;
```

2024-05-19 16:30 UTC, ChrisThrasher commented
> Great change! This makes the API much nicer and safer to use. The only thing I think we can improve is that we don't need a default constructor at all, we always need font handles and a family name to construct the font AFAICS. Please let me know if I am mistaken!

Sounds good. Happy to drop that default ctor in favor of something more useful.

2024-05-19 16:31 UTC, ChrisThrasher commented on include/SFML/Graphics/Font.hpp
> +    Font() = default;
Why use `explicit` when there are 2 parameters? I'm only familiar with `explicit` on single-parameter constructors.

2024-05-19 17:33 UTC, vittorioromeo approved these changes
LGTM!

2024-05-19 20:01 UTC, merged