Simplify implementations of types without an empty state
SFML/SFML pull request #3037
Opened 2024-05-23 03:37 UTC by ChrisThrasher

## Description

Now that these types have no default empty state, we can make assumptions about certain data members which allow us to skip doing certain checks.

I discovered this while iterating on #3032. It was something I overlooked in previous PRs.

2024-05-23 23:34 UTC, vittorioromeo requested changes
This is a good change and a sign that removing empty states was the right thing to do, but we should replace every check with an `assert` rather than removing it outright.

Even if we know that, e.g., `m_shaderProgram` cannot be empty in `setUniform`, its type still allows the empty state as part of its domain.

I am happy to approve if the assertions are added.

2024-05-24 00:14 UTC, ChrisThrasher commented
> I am happy to approve if the assertions are added.

Sure I can add those asserts. In doing so I realized that the `Shader` destructor should still check for `m_shaderProgram` being zero since a moved-from shader sets that value to zero. Is it a bug to call `GLEXT_glDeleteObject(castToGlHandle(m_shaderProgram))` when `m_shaderProgarm` is zero? Idk. But I'd rather play it safe for now.

2024-05-24 00:18 UTC, vittorioromeo commented
> > I am happy to approve if the assertions are added.
> 
> Sure I can add those asserts. In doing so I realized that the `Shader` destructor should still check for `m_shaderProgram` being zero since a moved-from shader sets that value to zero. Is it a bug to call `GLEXT_glDeleteObject(castToGlHandle(m_shaderProgram))` when `m_shaderProgarm` is zero? Idk. But I'd rather play it safe for now.

I found this: https://developer.download.nvidia.com/opengl/specs/GL_ARB_shader_objects.txt

>   37) What should the behavior of glDeleteObject(0) be?
> 
>     DISCUSSION: It would be desirable to allow 0 as a valid input value, and
>     not raise an error.
> 
>     RESOLUTION: glDeleteObject() will silently ignore deleting the value 0.
>     This is consistent with glDeleteTextures() that also silently ignores
>     deleting the value 0.

2024-05-24 00:19 UTC, vittorioromeo requested changes
Missed one :)

2024-05-24 00:19 UTC, vittorioromeo commented on src/SFML/Graphics/Font.cpp
> +    FT_Face face = m_fontHandles->face;
```suggestion
    assert(m_fontHandles);

    FT_Face face = m_fontHandles->face;
```

2024-05-24 00:35 UTC, vittorioromeo approved these changes

2024-05-24 02:04 UTC, merged