renamed getLoop() to isLooping() and setLoop() to setLooping()
SFML/SFML pull request #3187
Opened 2024-08-05 19:16 UTC by pinsvin00

## Description
This PR is related to the issue #3184
https://github.com/SFML/SFML/issues/3184

## Tasks

-   [ ] Tested on Linux
-   [X] Tested on Windows
-   [ ] Tested on macOS
-   [ ] Tested on iOS
-   [ ] Tested on Android

## How to test this PR?
Some usage of setLooping() is already present in SoundEffects.cpp example project. Please check this example project.

2024-08-05 19:30 UTC, ChrisThrasher commented
SFMLBuildMaster: Build this please.

2024-08-05 19:42 UTC, ChrisThrasher commented
Looks like you need to update the unit tests. If you build SFML with the `dev` preset then CMake will automatically enable all the extra developer tools including the tests. I'd recommend using that preset any time you want to work on the library.

2024-08-06 11:32 UTC, pinsvin00 commented
Thanks for noticing, I had some issues with cmake so I missed all of the tests.

2024-08-06 23:42 UTC, ChrisThrasher commented
SFMLBuildMaster: Build this please.

2024-08-06 23:43 UTC, ChrisThrasher requested changes

2024-08-06 23:43 UTC, ChrisThrasher commented on include/SFML/Audio/Music.hpp
> +/// music.setLooping(true);           // make it loop
```suggestion
/// music.setLooping(true);        // make it loop
```

2024-08-06 23:45 UTC, ChrisThrasher approved these changes

2024-08-06 23:45 UTC, ChrisThrasher commented
SFMLBuildMaster: Build this please.

2024-08-08 19:58 UTC, ChrisThrasher commented
SFMLBuildMaster: Build this please.

2024-08-08 19:58 UTC, ChrisThrasher approved these changes

2024-08-08 21:01 UTC, merged

2024-08-08 21:24 UTC, eXpl0it3r commented
Thank you! 😊