Use backticks for SFML types in doc comments
SFML/SFML pull request #3213
Opened 2024-09-08 21:56 UTC by eXpl0it3r

## Description

Similar to #3190, I added backticks to all the SFML types.  
Since this was manual work, there's a high chance that I've missed some spots.

I've also spotted a few inconsistencies and tried to align them, but might have also still missed some.

This PR closes #3123

## How to test this PR?

Generate the docs and ensure it looks correct.

2024-09-08 22:29 UTC, ChrisThrasher requested changes
I like the premise of this PR and think the liberal use of monospacing will make the generated documentation easier to read.

2024-09-08 22:29 UTC, ChrisThrasher commented on include/SFML/Audio/Listener.hpp
> +/// The \a `volume` is a number between 0 and 100; it is combined
```suggestion
/// \a `volume` is a number between 0 and 100; it is combined
```

2024-09-08 22:29 UTC, ChrisThrasher commented on include/SFML/Audio/Listener.hpp
> +/// The default listener's position is `(0, 0, 0)`.
I'm not sure if "(0, 0, 0)" counts as code. I suppose it count be interpreted as part of a bigger expression like `sf::Vector3(0, 0, 0)`.

2024-09-08 22:29 UTC, ChrisThrasher commented on include/SFML/Audio/Listener.hpp
> +/// `sf::Listener` is his ears (by the way, they are often linked
```suggestion
/// `sf::Listener` are their ears (by the way, they are often linked
```

2024-09-10 01:59 UTC, ChrisThrasher commented
I generated the docs and am clicking around to see what I can find. Here are some observations.

* "*this" is often not monospaced
* "True"/"true"/"False"/"false" is often not monospaced within `\return` lines
* Look for instances of "operator *", "operator ==" and other similar strings in the docs. Note the extra space after "operator" which I think should be removed
* There are other uses of stuff like "== operator" which I think ought to be "`operator==`".
* The following regex `///.* sf::` finds more uses of non-monospaced references to 1st party types. For example, InputSoundFile.hpp class docs at the bottom of the file.
* Glsl.hpp referes to types like `Mat3` without a `sf::` namespace so they missed the regexes you used to find them. I think that file ought to add `sf::` prefixes when referring to 1st party types.
* The `sf::ContextSettings` docs refer to data members. We could monospace those as well. I'm not sure how to easily find other instances of this occurring so doing this repo-wide will take a lot of manual inspection.

I'm not necessarily sure that all of these points should result in a change to this PR but I thought they were worth sharing nonetheless.

2024-09-10 21:35 UTC, eXpl0it3r commented
> * Glsl.hpp referes to types like `Mat3` without a `sf::` namespace so they missed the regexes you used to find them. I think that file ought to add `sf::` prefixes when referring to 1st party types.
> * [ ]  The `sf::ContextSettings` docs refer to data members. We could monospace those as well. I'm not sure how to easily find other instances of this occurring so doing this repo-wide will take a lot of manual inspection.

I feel like these take way too much time to figure out and there's little regex magic to apply. We can try to improve as we go or if someone is bored, they can tackle it, but I'd leave it as is for the current PR.

2024-09-10 22:41 UTC, ChrisThrasher requested changes
See also HIDInputManager.hpp:101 and HIDInputManager.hpp:125

2024-09-10 22:41 UTC, ChrisThrasher commented on include/SFML/Audio/InputSoundFile.hpp
> +    /// position during spatialization.
This spelling is also found in AudioDevice.hpp

2024-09-10 22:41 UTC, ChrisThrasher commented on include/SFML/Window/WindowBase.hpp
>  /// A sf::WindowBase can create its own new window, or be embedded into
```suggestion
/// An `sf::WindowBase` can create its own new window, or be embedded into
```
Should we also audit the docs for the use of "a" prior to an `sf::` type? I think it reads better to as "an" as the article.

2024-09-11 15:42 UTC, ChrisThrasher commented
Switching to macOS (and therefore upgrading to Doxygen 1.12) fixes the Doxygen error we were getting.

2024-09-11 19:32 UTC, ChrisThrasher commented
Adding backticks around "sf::Exception" does not work. Those backticks also result in a hyperlink to `sf::Exception` not being formed.

<img width="525" alt="Screenshot 2024-09-11 at 1 31 13 PM" src="https://github.com/user-attachments/assets/0cf69125-4050-4499-bad6-639f07ad031f">

2024-09-11 19:41 UTC, ChrisThrasher approved these changes
I think in its current state this PR makes enough progress that it's ready to merge. We will keep iterating on the docs in subsequent PRs.

2024-09-11 20:30 UTC, ChrisThrasher approved these changes

2024-09-11 22:02 UTC, merged