Use lazy loading for keyboard m_keys on macos
SFML/SFML pull request #3232
Opened 2024-09-14 20:47 UTC by Lorenzooone

## Description

On macos, initializing the keyboard's m_keys (a dictionary to convert scancodes to IOHIDElementRef) has the unfortunate side effect of triggering a request for "input monitor" permissions.
The m_keys dictionary is exclusively used when using isKeyPressed, which is a function that already triggers the input monitor permission request.
This change makes it so initialize_keyboard is only lazily called if isKeyPressed is called.

The benefit of this change is that using keyboard events on macos won't trigger permission requests, anymore (but isKeyPressed still will, like before).
initialize_keyboard is protected by a bool, so there are no risks of calling it more than needed (that is... once).

This PR fixes https://github.com/SFML/SFML/issues/2843

## Tasks

-   [X] Tested on macOS

## How to test this PR?

Try running a simple program on macos (like the Island example) which uses events for keyboard inputs.
You should not see any permission request popup.

Then, try running another program on macos which uses isKeyPressed.
After confirming input monitoring is allowed through the popup, you should be able to use isKeyPressed just fine.

2024-09-15 12:44 UTC, eXpl0it3r commented
SFMLBuildMaster: Build this please.

2024-09-16 16:10 UTC, ChrisThrasher requested changes
Glad to see someone take a shot at fixing this. This will be a good user experience win.

2024-09-16 16:10 UTC, ChrisThrasher commented on src/SFML/Window/macOS/HIDInputManager.hpp
> +    bool            m_keysInitializeTried; // Has initializeKeyboard been called at least once?
```suggestion
    bool            m_hasInitializedKeys{}; // Has initializeKeyboard been called at least once?
```
Let's use a variable name that reads a bit more like English.

2024-09-16 16:10 UTC, ChrisThrasher commented on src/SFML/Window/macOS/HIDInputManager.mm
> +    m_keysInitializeTried     = false;
```suggestion
```

2024-09-16 19:50 UTC, ChrisThrasher approved these changes
I was just able to confirm this patch works on my machine. Thank you!

2024-09-16 19:53 UTC, ChrisThrasher commented
SFMLBuildMaster: Build this please.

2024-09-16 20:35 UTC, merged