change glCheck macro to be usable as an expression
SFML/SFML pull request #3239
Opened 2024-09-20 23:56 UTC by ZXShady

this change allows [e]glCheck macros to be usable as expressions which makes writing code more natural example

```cpp
GLEXT_GLhandle shaderProgram{};
glCheck(shaderProgram = GLEXT_glCreateProgramObject());
```
into the more natural (and bonus it is const!)
```cpp
const GLEXT_GLhandle shaderProgram = glCheck(GLEXT_glCreateProgramObject());
```

2024-09-21 09:12 UTC, Bambo-Borris commented
Do these changes retain the behaviour @vittorioromeo added regarding ensuring we loop to get all errors? Otherwise we're undoing work just merged to correct the use of glCheck.

2024-09-21 11:12 UTC, ZXShady commented
Vittorio didn't add the looping mechanism because he wanted to make his pr self contained. this pr was just to make it usable as an expression so I didn't add the loop as well but it is easy to add it should I add it?

2024-09-21 11:17 UTC, Bambo-Borris commented
> Vittorio didn't add the looping mechanism because he wanted to make his pr self contained. this pr was just to make it usable as an expression so I didn't add the loop as well but it is easy to add it should I add it?

Personally, I'd prefer the looping behaviour be implemented after what Vee has done. Maybe the expression work you want in can be done after, but I think ensuring we align with how OGL docs intend you to use these error checking functions matters more in my view. Ultimately, it'll be the maintainers choice what order it happens in though.

2024-09-23 17:09 UTC, ChrisThrasher commented
@vittorioromeo Do you plan on submitting a PR for the looping behavior you described in https://github.com/SFML/SFML/pull/3233?

2024-09-23 17:09 UTC, ChrisThrasher requested changes

2024-09-23 17:09 UTC, ChrisThrasher commented on src/SFML/Window/EGLCheck.hpp
> +            ::sf::priv::eglCheckError(__FILE__, static_cast<unsigned int>(__LINE__), #__VA_ARGS__); \
```suggestion
            const auto eglCheckInternalReturnValue = eglCheckInternalFunction();                          \
            sf::priv::eglCheckError(__FILE__, static_cast<unsigned int>(__LINE__), #__VA_ARGS__); \
```

2024-09-23 17:09 UTC, ChrisThrasher commented on src/SFML/Window/EGLCheck.hpp
> +            ::sf::priv::eglCheckError(__FILE__, static_cast<unsigned int>(__LINE__), #__VA_ARGS__); \
```suggestion
            sf::priv::eglCheckError(__FILE__, static_cast<unsigned int>(__LINE__), #__VA_ARGS__); \
```

2024-09-24 16:50 UTC, ChrisThrasher approved these changes
@binary1248 @vittorioromeo You two have stronger opinions than me on matters of OpenGL so I'm curious what you think of this.

2024-09-25 04:02 UTC, ChrisThrasher commented
SFMLBuildMaster: Build this please.

2024-09-25 15:47 UTC, merged