Enable range based looping of `sf::VertexArray`
SFML/SFML pull request #3366
Opened 2024-12-26 20:39 UTC by ChrisThrasher

## Description

`begin` and `end` iterators are all that is required of a container to supported C++11 ranged-for loops.

2024-12-27 11:03 UTC, kimci86 commented
`VertexArray::operator[]` is not covered by tests now.

2024-12-27 20:01 UTC, kimci86 commented
> This operator is still used indirectly by some other tests.

Which one? Coveralls report does not see it.

2024-12-27 20:53 UTC, ChrisThrasher commented
> > This operator is still used indirectly by some other tests.
> 
> Which one? Coveralls report does not see it.

https://github.com/SFML/SFML/blob/3c084bf66186378dc52a53175ad396b344cb6a73/test/Graphics/VertexArray.test.cpp#L78

It’s used in a few places.

2024-12-28 11:02 UTC, kimci86 commented
Ok, this is because the non-const variant is used by tests but the const variant is not.

2024-12-29 16:16 UTC, ChrisThrasher commented
> Ok, this is because the non-const variant is used by tests but the const variant is not.

Ah okay this makes sense. I added tests explicitly for this case to make sure it remains covered. Thanks for catching this!

2025-02-18 14:35 UTC, ZXShady requested changes

2025-02-18 14:35 UTC, ZXShady commented on test/Graphics/VertexArray.test.cpp
> +        CHECK(count == vertexArray.getVertexCount());
count is incremented twice it would be 2 * getVertexCount()

2025-02-21 14:33 UTC, ZXShady commented on test/Graphics/VertexArray.test.cpp
> +            for (const auto& vertex : vertexArray)
I think it is better to test whether `auto&` non const compiles because it means that the dereferenced iterators correctly return a non const lvalue reference.

2025-02-22 20:55 UTC, ZXShady approved these changes

2025-04-01 11:14 UTC, eXpl0it3r commented
Am I understanding it correctly, that this opens up additional opens to manipulate the VertexArray's vertices? Anything that takes a `begin()`-`end()` "range", right? Is there anything we need to consider in those cases?

What I mean, the PR focuses on ranged-based looping, but the feature itself goes beyond that. So I just want to make sure when people do manipulate the vertices through that interface, nothing breaks. I currently don't see anything, but maybe someone else can think of some potential problem.

2025-04-01 12:38 UTC, ZXShady commented
> Am I understanding it correctly, that this opens up additional opens to manipulate the VertexArray's vertices? Anything that takes a `begin()`-`end()` "range", right? Is there anything we need to consider in those cases?
> 
> What I mean, the PR focuses on ranged-based looping, but the feature itself goes beyond that. So I just want to make sure when people do manipulate the vertices through that interface, nothing breaks. I currently don't see anything, but maybe someone else can think of some potential problem.

they can't break anything 

begin and end are just equalivent semanticly to `&vertex_array[0]` and `&vertex_array[vertex_array.size()]` respectivly but less annoying to type.

2025-04-01 15:17 UTC, eXpl0it3r approved these changes
Seems like a useful addition 👍

2025-04-01 15:49 UTC, merged